# error.py
print("hello world")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print(hello for the last time)