# error.py
print("hello world")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("hello again")
print("1" + 2)
